---
abstract: 'Generalized Inverted Indexing'
author:
  - 'Yuval Kogman <nothingmuch@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  MooseX::Types::Set::Object: 0
  Test::More: 0
  Test::TempDir: 0
  ok: 0
  overload: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.101610'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-GIN
requires:
  Carp: 0
  Data::Stream::Bulk::Util: 0
  MRO::Compat: 0
  Moose: 0
  Moose::Role: 0
  Scalar::Util: 0
  Scope::Guard: 0
  Set::Object: 0
  Test::Deep::NoTest: 0
  namespace::clean: 0
version: 0.06
