--- #YAML:1.0
name:                Search-GIN
version:             0.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Data::Stream::Bulk:            0.03
    Moose:                         0
    MooseX::Types::Path::Class:    0
    MooseX::Types::Set::Object:    0
    MRO::Compat:                   0
    namespace::clean:              0.08
    Scope::Guard:                  0
    Set::Object:                   0
    Test::More:                    0
    Test::TempDir:                 0
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
